using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;

namespace StubId.CaptureHarness;

/// <summary>
/// Decodes the certificates embedded in a recorded JWKS.
/// </summary>
/// <remarks>
/// Worth doing explicitly rather than eyeballing the JSON. The certificate subjects are
/// what identify which key signs which token type, and reading them is what showed that the
/// transaction-token key is published in the JWKS after all — the vendor's own documentation
/// lists a thumbprint that has since been rotated away.
/// </remarks>
public static class CertificateReport
{
    /// <param name="jwksBody">The key set as the broker served it.</param>
    /// <param name="environment">Which environment this key set belongs to.</param>
    /// <param name="captureId">The case that recorded it, so the file says where it came from.</param>
    public static string Build(byte[] jwksBody, string environment, string captureId)
    {
        using var document = JsonDocument.Parse(jwksBody);
        var report = new StringBuilder();

        report.Append("# Signing certificates in the ").Append(environment).AppendLine(" JWKS");
        report.AppendLine();
        report.Append("Generated by the capture harness from ").Append(captureId)
            .AppendLine(". Do not edit by hand.");
        report.AppendLine();

        var keys = document.RootElement.GetProperty("keys").EnumerateArray().ToList();

        // Where not one key carries a chain, a stanza per key would repeat that absence for every
        // one of them. A table says the same thing once and still names each key.
        if (keys.All(key => !key.TryGetProperty("x5c", out _)))
        {
            report.Append("None of the ").Append(keys.Count)
                .AppendLine(" keys publishes an x5c chain, so there is no certificate to decode.");
            report.AppendLine();
            report.AppendLine("| kid | kty | use | alg member present |");
            report.AppendLine("| --- | --- | --- | --- |");

            foreach (var key in keys)
            {
                report.Append("| `").Append(Member(key, "kid"))
                    .Append("` | `").Append(Member(key, "kty"))
                    .Append("` | `").Append(Member(key, "use"))
                    .Append("` | ").Append(key.TryGetProperty("alg", out _) ? "yes" : "no")
                    .AppendLine(" |");
            }

            return report.ToString();
        }

        foreach (var key in keys)
        {
            var kid = key.TryGetProperty("kid", out var k) ? k.GetString() : null;
            var use = key.TryGetProperty("use", out var u) ? u.GetString() : null;
            var hasAlg = key.TryGetProperty("alg", out _);

            report.Append("## ").AppendLine(kid);
            report.AppendLine();
            report.Append("- use: `").Append(use).AppendLine("`");
            report.Append("- alg member present: ").AppendLine(hasAlg ? "yes" : "no");

            // A key set need not publish a chain at all. The first broker's does, and reading
            // it unguarded would have crashed a first capture of one that does not - at the key
            // set, which is the second case, leaving a pack half written.
            if (!key.TryGetProperty("x5c", out var chain))
            {
                report.AppendLine("- x5c: none published, so there is no certificate to decode");
                report.AppendLine();
                continue;
            }

            report.Append("- x5c length: ").AppendLine(chain.GetArrayLength().ToString());

            foreach (var element in chain.EnumerateArray())
            {
                var raw = Convert.FromBase64String(element.GetString()!);
                using var certificate = X509CertificateLoader.LoadCertificate(raw);

                report.Append("- subject: `").Append(certificate.Subject).AppendLine("`");
                report.Append("- issuer: `").Append(certificate.Issuer).AppendLine("`");
                report.Append("- valid: ")
                    .Append(certificate.NotBefore.ToString("yyyy-MM-dd"))
                    .Append(" to ")
                    .AppendLine(certificate.NotAfter.ToString("yyyy-MM-dd"));
                report.Append("- thumbprint matches kid: ")
                    .AppendLine(string.Equals(certificate.Thumbprint, kid, StringComparison.OrdinalIgnoreCase)
                        ? "yes"
                        : $"no (thumbprint {certificate.Thumbprint})");
            }

            report.AppendLine();
        }

        return report.ToString();
    }

    private static string? Member(JsonElement key, string name) =>
        key.TryGetProperty(name, out var value) ? value.GetString() : null;
}
