using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;

namespace StubId.CaptureHarness;

/// <summary>
/// Decodes the certificates embedded in a recorded JWKS.
/// </summary>
/// <remarks>
/// Worth doing explicitly rather than eyeballing the JSON. The certificate subjects are
/// what identify which key signs which token type, and reading them is what showed that the
/// transaction-token key is published in the JWKS after all — the vendor's own documentation
/// lists a thumbprint that has since been rotated away.
/// </remarks>
public static class CertificateReport
{
    public static string Build(byte[] jwksBody)
    {
        using var document = JsonDocument.Parse(jwksBody);
        var report = new StringBuilder();

        report.AppendLine("# Signing certificates in the pre-production JWKS");
        report.AppendLine();
        report.AppendLine("Generated by the capture harness from CAP-002. Do not edit by hand.");
        report.AppendLine();

        foreach (var key in document.RootElement.GetProperty("keys").EnumerateArray())
        {
            var kid = key.GetProperty("kid").GetString();
            var use = key.TryGetProperty("use", out var u) ? u.GetString() : null;
            var hasAlg = key.TryGetProperty("alg", out _);
            var chain = key.GetProperty("x5c");

            report.Append("## ").AppendLine(kid);
            report.AppendLine();
            report.Append("- use: `").Append(use).AppendLine("`");
            report.Append("- alg member present: ").AppendLine(hasAlg ? "yes" : "no");
            report.Append("- x5c length: ").AppendLine(chain.GetArrayLength().ToString());

            foreach (var element in chain.EnumerateArray())
            {
                var raw = Convert.FromBase64String(element.GetString()!);
                using var certificate = X509CertificateLoader.LoadCertificate(raw);

                report.Append("- subject: `").Append(certificate.Subject).AppendLine("`");
                report.Append("- issuer: `").Append(certificate.Issuer).AppendLine("`");
                report.Append("- valid: ")
                    .Append(certificate.NotBefore.ToString("yyyy-MM-dd"))
                    .Append(" to ")
                    .AppendLine(certificate.NotAfter.ToString("yyyy-MM-dd"));
                report.Append("- thumbprint matches kid: ")
                    .AppendLine(string.Equals(certificate.Thumbprint, kid, StringComparison.OrdinalIgnoreCase)
                        ? "yes"
                        : $"no (thumbprint {certificate.Thumbprint})");
            }

            report.AppendLine();
        }

        return report.ToString();
    }
}
